jbaublitz/neli

src/c/netlink.c
src/ffi.rs
src/lib.rs
src/socket.rs

Hi. I'm writing a wrapper for `libnftnl` in Rust to be able to control the Linux firewall. To do that I need to talk netlink. Since `libnftnl` uses `libmnl` for that natively I could just write a wrapper for `libmnl` as well. But the more pure-rust I can use the better was my thought. And it also feels like there are already too many libraries duplicating the `NlFamily` enum. So I looked for pure Rust netlink libraries.
After looking at yours for a while I see that many of the constants you declare are already in libc. So I thought I could try to make it use them instead. I don't know if you want this change or not, but it reduces duplication at least. We could quite likely get the remaining constants merged into libc as well, I have had constants from for example `<linux/netfilter/*>` …

Use constants from libc where they exist

---

src/err.rs
src/ffi.rs
src/genlhdr.rs
src/lib.rs
src/nlhdr.rs
src/socket.rs

I noticed `self.push('\0');` in the serialization of `String`. I personally found it to be a strange property that serializing a type could possibly modify it. Because serializing the same instance multiple times could then yield different results. In the case of `String`, calling `Nl::size` on a `String` would differ before and after the serialization.
Here I make `&mut self` into `&self` in `Nl::serialize` to prohibit mutation of `self`. The only type affected by this was indeed `String`, which I solved by re-allocating the string buffer into one with the terminating null in the serialization implementation.
I was also looking into making the `deserialize` impl for `String` make use of `CString`. But I was not really sure how the lengths of the deserialization state worked. Especially …

Make serialize work without mutating input

---

src/lib.rs

One of the common types found when dealing with Generic Netlink is `u64`. This PR adds an implementation of the `Nl` trait for `u64` so that these values can be easily deserialized by `neli` when reading Netlink messages.
You can use the new `impl` to parse Netlink attrs link this:
```
let peer_attr_handle: neli::nlattr::AttrHandle<'_, u16> = ...;
let recieved_bytes: u64 = peer_attr_handle.get_payload_with::<u64>(PEER_RECIEVED_BYES_ATTR, None).unwrap();
```
The implementation is defined in basically the same way as the other impls for unsigned integers are. 
A test that works like the others was also added to `src/lib.rs`.
This pr addresses #11.

Created `impl Nl for u64`

---

src/nlattr.rs

The template type for `get_nested_attributes` was previously used in neli to specify the Netlink attribute type for the nested attributes. It's currently unused in neli 0.4.2. I think this may have been a typo since forcing all nested types to be T makes parsing nested attributes of a different type than the parent impossible.
If I'm wrong, please feel free to close the pull request.

Use get_nested_attributes R type for message type

---

examples/Cargo.toml
examples/route-list.rs
src/rtnl.rs

The Rtattr types needed some help with their padding and size hints.  I tried to follow the responsibility rules you laid out in nlattrs.rs.  I added some tests as well.
I added a sample below, `route-list`, which is a cheap imitation of the `ip route` command.  Seems to work for me, but I've not tested it extensively!

Small fixes for rtnetlink, and add route-list example to exercise it.

---

src/err.rs

It comes handy when playing with the protocol.
It would be even better if it could also implement the `Error` and `Display` traits. It seems the error is negative errno, so it could be resolved by using the `std::io::Error`. Is it OK to change the struct to contain that instead of the direct error code? Or maybe add an `Into` implementation?

Nlmsgerr can implement debug

---

src/consts/macros.rs
src/rtnl.rs

This PR contains two things:
* Derive (Partial)Eq, (Partial)Ord and Hash traits for enums. Deriving these five traits allow using these enums in HashMaps and BTreeMaps.
* Derive Debug for structs in routing netlink subsystem. These make it much easier to figure out what happens by logging or print debugging.

Derive implementations

---

src/socket.rs

Return size_t instead of ssize_t. All the negative values of the latter
are considered errors, so never leave the function.
Closes #47.

Return unsigned types in NlSocket::{send, recv}

---

examples/route-list.rs
src/rtnl.rs

Rtattrs have specific type depending on the struct. Remove type variable to simplify using these structs and remove possibility to make mistakes.
I made the mistake of using wrong type and spend embarrassingly amount of time figuring out what happens. I opened this PR which implements simpler structs for `rtnl` so that I can give it a more test.
Related to #54.

Simplify structs by removing type variables in rtnl

---

src/consts/rtnl.rs

This information can be found from `rtnetlink(7)` manpage, but small hint in the docs doesn't hurt?

Document which Rtattr.rta_type goes with what rtnetlink struct.

---

CHANGELOG.md
examples/nflog.rs
src/consts/mod.rs
src/consts/netfilter.rs
src/lib.rs
src/netfilter.rs

Hello
This adds the support for basic use of the nflog protocol. There are still some parts missing, but I'd prefer to have a feedback about it sooner than later and I tried to make sure all the missing pieces can be added without breaking API.
I've also tried to structure it in a way that makes it possible/natural to add all the other netfilter protocols over time (NFQUEUE, CONNTRACK).
There are, however, few things I'm not entirely happy about or don't know how to handle properly. I'll probably open separate issues to discuss them one by one, if there's some nice solution for them. But I'll still list my worries here first.
* When receiving messages over the socket, I have to specify into what type I want them to deserialize. But this might depend on the type. This can be seen on the …

Nflog support MVP

---

src/consts/rtnl.rs
src/rtnl.rs

As documented in #56, `Ndmsg` struct is broken. This PR fixes it by adding the missing `rtattr` field for the struct, add the missing `rta_type` for `Rtattr`s as well as fixing the alignment of the struct with correct padding. Finally of course fixing the length calculations.
I couldn't find any docs (or use case) for `Ndmsg.ndm_type`, so I changed it to `u8`. It's there, but no idea what it should be used for.
Fixes #56

Fix `Ndmsg` struct

---

Cargo.toml
src/consts/netfilter.rs

Libc released a version with the symbolic constants for the nfnetlink
log protocol, we can now use them instead of hardcoding the numbers
here. No functional change.
Closes #59.

nflog: Use constants from libc

---

Cargo.toml
src/consts/rtnl.rs

See https://github.com/torvalds/linux/blob/54ecb8f7/include/uapi/linux/if_link.h#L354-L362

Add IFLA_INFO_ consts

---

src/socket.rs

Sequence numbers are used for two purposes from what I can tell. One is associating a set of response messages with a request message. The other is an incrementing counter when subscribing to a multicast group stream. As a result, recv_nl should never increment the counter when receiving a message as send_nl will increment it when sending it. All responses should have the same sequence number as the request. In the case of multicast groups, no ACKs are sent so no increment operations are needed.

Fix bug in sequencing handling

---

.travis.yml
Cargo.toml
examples/Cargo.toml
src/lib.rs
src/socket.rs
test/Makefile

This PR adds the ability to compile neli with the `logging` feature to add output for all of the messages sent and received. This should be extremely useful for debugging.
The reason this targets 0.5.0 is that it requires a small breaking change for the API to require all data structures being used with `send_nl` and `recv_nl` to implement `Debug`.

Add debug logging to neli

---

src/socket.rs

PR revisions for #66 
@vorner I really don't think `IntoRawFd` should have been implemented in the first place. I really don't feel good about leaking IO resources so I'm going to remove it altogether. `AsRawFd` should do almost exactly the same thing without breaking resource cleanup. Is there a reason you were looking for this functionality? If so could you provide me with an example?
Either way, thank you for bringing this to my attention!

Remove IntoRawFd

---

src/consts/rtnl.rs
src/rtnl.rs

Ifaddrmsg currently uses IfaFFlags for its ifa_flags field, but the
structure on the wire only has one-byte flags, not four-byte flags.
(Four-byte flags get sent as an attr.)
Fix the serialization and deserialization of Ifaddrmsg, Add From and
TryFrom impls to convert IfaFFlags to and from libc::c_uchar.
Closes #109

Fix size of ifa_flags field in Ifaddrmsg

---

src/rtnl.rs

Ifinfomsg was serializing two copies of ifi_change; drop the incorrect
one.

Ifinfomsg: Remove duplicate serialization of ifi_change field

---

src/rtnl.rs

Commit a53abe0ed416040b5edd9f7c5e0d5f05fbab6eb5 introduced two non-public fields to `Ndmsg` struct (`pad1` and `pad2`). This has made it impossible to construct `Ndmsg` struct outside `neli` from version 0.5 and later. This PR introduces `Ndmsg::new()` method to construct the struct.

Add Ndmsg::new function to initialize Ndmsg

---

examples/custom_generic_nl_family_custom_types.rs

I'd like to add an example on **how to use neli with custom properties for custom generic netlink families**. I use this at an uni project where I develop a kernel module (which registers a custom generic netlink family), a userland component in Rust (using neli), and a other userland component using libnl. Therefore I can ensure that my approach works with the kernel / other netlink implementations.
Let's assume we have a custom kernel driver that registers a `"your_family_name_here"` family. The subject of our problem knows the operations/commands `echo`, `create device`, and `delete device`. It also knows the attributes `msg (string)` and `device name (string)`. 
In this example (see code) an `echo` message is send to the kernel and the reply received:
_PS: Example kernel module that …

Example for custom generic netlink family with custom attributes

---

examples/ctrl-list.rs
examples/custom_generic_nl_family_custom_types.rs
examples/error_packet.rs
examples/genl_stream.rs
examples/getips.rs
examples/lookup_id.rs
examples/neli.rs
examples/route-list.rs
src/genl.rs
src/lib.rs
src/socket.rs
src/utils.rs

Closes #141 
This includes a breaking change, but given that it is a bug fix, this will go into the next patch release.

Fix for set/getsockopt wrappers for netlink sockets

---

examples/getips.rs

getips ignores anything that isn't an NlPayload::Payload, which includes
NlPayload::Err. Instead, skip over NlPayload::Empty but process other
errors as errors.

getips: Don't ignore errors returned after iteration starts

---

neli-proc-macros/Cargo.toml

neli-proc-macros does not compile with syn 1; it needs newer
functionality. Bump it to the current version.

neli-proc-macros: Update required version of `syn`

---

examples/create-nested-attributes.rs
examples/custom_generic_nl_family_custom_types.rs
examples/extack.rs
src/genl.rs
src/socket.rs
src/types.rs

Most netlink protocols use native-endian; simplify the common case.

Default to native-endian in `Nlattr::new`; add `new_be` for network-endian

---

src/err.rs

According to man 7 netlink, in case of error, the error field represents "negative errno". Also a simple test trying to add an interface as an unprivileged user, I get that field as -1 which the Display function translates into "Unknown error". With the change proposed, I get  "Operation not permitted" which is what one would expect.

Fix error field interpretation

---

Cargo.toml
src/lib.rs

Bump byteorder dependency to 1.3, since that version added automatic
128-bit support.

Support FromBytes and ToBytes for i128 and u128

---

src/socket/shared.rs

Set the option SOCK_CLOEXEC on the newly created netlink socket, so that it does not leak on concurrent execve(2) calls in a sibling thread.

Close netlink socket on execve

---

examples/getips.rs
src/router/asynchronous.rs
src/router/synchronous.rs
src/rtnl.rs
src/socket/asynchronous.rs
src/socket/shared.rs
src/socket/synchronous.rs

Supported since Linux 4.20.
See https://kernel.org/doc/html/next/userspace-api/netlink/intro.html#strict-checking

Add methods to control strict input checking for route sockets

---

examples/neli.rs
src/genl.rs
src/router/asynchronous.rs
src/router/synchronous.rs
src/rtnl.rs

While using this I noticed that the `.get_nested_attributes` took mutable references, but I don't think the `mut` is required here. 
This PR removes it (and _**targets the `v0.7.0-rc2` branch**_).
---
By the way, `v0.7.0-rc2` is looking really good IMO!

`get_nested_attributes` doesn't need `&mut self`

---

src/err.rs
src/genl.rs
src/iter.rs
src/nl.rs
src/router/mod.rs
src/router/synchronous.rs
src/rtnl.rs
src/socket/synchronous.rs

Fix documentation errors in nightly

---

src/router/asynchronous.rs
src/router/synchronous.rs
src/rtnl.rs

Bug fix for race condition and unpredictable presence of DONE packet.

---

Cargo.toml

Debian packages 0.20.1, Fedora packages 0.20.2, which makes impractical to stick to 0.11. I did some quick tests and everything seems to work with 0.20.
Supersedes #264: the commit included there is empty.

Cargo.toml: Bump derive_builder dependency version to 0.20

---

src/rtnl.rs

Provided by Kitlith <kitlith@kitl.pw> on:
https://github.com/jbaublitz/neli/issues/273
...if we build input buffers for Rtattr::from_bytes byte-by-byte in the test_rta_deserialize and test_rta_deserialize_err tests, they will fail unless we adapt to the current endianness. Specifically, the existing version would fail on big-endian machines.
Given that Rtattr::from_bytes is supposed to take native-endian values, build values accordingly.
Link: https://github.com/jbaublitz/neli/issues/273
Analysed-by: Fabio Valentini <decathorpe@gmail.com>
Analysed-by: Kitlith <kitlith@kitl.pw>

rtnl: Pass native-endian values to Rtattr::from_bytes in tests

---

src/iter.rs
src/router/asynchronous.rs
src/router/synchronous.rs
src/socket/asynchronous.rs
src/socket/synchronous.rs

The problem with logging at debug level is that we have neli as part of a much bigger binary, and right now neli dumps very big unformatted structs in syslog.
We believe that neli should instead log these items at a lower level, such as trace!(). Debug-level log messages are still relevant for end users of the system, but trace messages are only for developers that know their way around on the system and thus are expected to know how to filter noise out (e.g. via environment variables to the logger).

fix: log naked structs at trace!() level

---

src/err.rs

Currently, for io::Error only the error kind is returned to the user. This is a lossy conversion and may leave the user with a Uncategorized error and no way to debug this further.
As io::Error is not cloneable, wrap it in an Arc.
---
I'm not sure if there was an deliberate decision behin only keeping the ErrorKind other than io::Error not being Cloneable. This is a user facing API change, but I hope this is okay in an rc.
In my case I've got a Uncategorized error in `recv` which was actually a `ENOBUFS`. This error means that I'm not reading from the netlink socket fast enough. Without this patch there is no way I would have diagnosed the problem, so I hope the API-Change is acceptable.

Pass full io::Error to user

---

src/socket/shared.rs

Closes #273
Related to #268 
@sbrivio-rh I've reproduced and fixed the failure on s390x. I believe that all tests now pass.

Fix bug in group handling with getsockopt syscall

---

src/lib.rs

Closes #210 
Since I've already implemented `Size` for `[u8; N]`, I think that we could also implement it for the other traits to make the crate smoother to use
About implementing them for `[T; N]`, I don't really know what would be the use case, so maybe not implementing it until someone ask for it is the right choice

Add const generic implementations for FromBytes and ToBytes traits for arrays

---

src/socket/asynchronous.rs
src/socket/shared.rs
src/socket/synchronous.rs

Closes #230 
I think that this was the intent of the issue author.
I've read a bit about the option, and it seems that we cannot rely on the kernel to set a specific size, so we cannot rely on that to simplify the logic in neli's buffers.
I didn't provide an option to set the send buffer size, because the default should be good enough (netlink isn't typically used to send large amounts of data).

Add option to set recv buffer size

---

examples/nl80211.rs

Expand the nl80211 example to include interface-level information printouts.
~~This is somewhat self-motivated, as I am having trouble with parsing the SSID field. Unlike interface and wiphy name attributes, the SSID is not NULL-terminated (note the partial SSID in the printout, should be `partialssid`). I'm sure with fresh eyes I can find it, but doesn't hurt to update the example haha!~~ See below comment on using `get_payload_as_with_len_borrowed()` with `&[u8]`.
Note that P2P device interfaces do not have an interface index or name when queried with `NL80211_CMD_GET_INTERFACE`, at least how I've updated the example.
```Bash
$ cargo run --example nl80211 --features async
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
Running `target/debug/examples/nl80211`
WiFi …
```

Expand nl80211 example
