jbaublitz/neli

src/consts.rs
=> Update consts.rs for ability to autogenerate documentation for macro-defined netlink constants

examples/ctrl-list.rs
Followup from: https://github.com/jbaublitz/neli/issues/15#issuecomment-490627034
=> Add genl ctrl list example

src/socket.rs
=> Make send/recv take a &self receiver

Cargo.toml, examples/Cargo.toml, examples/genl_stream.rs, src/err.rs, src/genl.rs, src/lib.rs, src/nl.rs, src/nlattr.rs, src/rtnl.rs, src/socket.rs
@another-s347 I've made changes to your PR but this should update everything to tokio 0.2. I'm in the process of reimplementing sink, but let me know if you'd like to see anything else before I merge.
=> Update tokio to 0.2

src/consts/rtnl.rs, src/rtnl.rs
@marcelbuesing I made one addition to your PR and rebased it. Take a look and let me know if you want to discuss anything else before I merge. Upon further reflection, convenience methods for commonly generated packets may make this library a whole lot more usable. Thank you for your contribution!
=> Fix for Ifinfomsg

src/socket.rs
=> Add CLOEXEC to socket creation

src/rtnl.rs
Rebased version of #69 
There are two issues in serializing and deserializing Tcmsg:
- The structure contains three padding bytes (expressed as a padding byte
followed by padding short) between the 1-byte tcm_family and 4-byte
tcm_ifindex. Fix by adding explicit serialize and deserialize calls
at appropriate places, and adding mem::size_of calls in Tcmsg::size().
- Tcmsg::deserialize does not update the size hint before invoking
Rtattrs::deserialize. Thus after parsing the actual attributes, 20 bytes
appear to be left, and parsing continues into unrelated data.
Signed-off-by: Petr Machata <pmachata@gmail.com>
=> rtnl: Fix parsing of Tcmsg

src/consts/macros.rs, src/nlattr.rs
Closes #84 
@gluxon @dhl How does this look to you?
=> Add bitflags packed into nla_type to Nlattr

examples/Cargo.toml, examples/getips.rs, src/consts/genl.rs, src/consts/macros.rs
Incorporates and closes #92.
@joshtriplett I wanted to release this morning as promised so I made a few edits just to the imports. As I mentioned to another contributor, I'm trying to put some coding style guidelines in place, but until then, I just thought it'd make sense to incorporate your original commit into a new PR and make some changes to the imports. 0.5.2 will be released shortly and thank you for your contributions!
=> Rtnl example

Cargo.toml, src/consts/macros.rs, src/consts/rtnl.rs, src/lib.rs, src/macros.rs
Update the libc dependency accordingly.
=> Add more IPLA flags, from newer libc

.github/workflows/main.yml, src/lib.rs
=> Fix clippy

.github/workflows/main.yml, Cargo.toml, examples/Cargo.toml, examples/genl_stream.rs, src/lib.rs, src/socket.rs
=> Update to tokio 1.0

src/socket.rs
Closes #108 
@joshtriplett @phip1611 Does this resolve the issue for you?
=> Add iter2()

src/rtnl.rs
=> Fix bug in Ifinfomsg

src/genl.rs, src/types.rs
=> Add methods to get AttrHandle and AttrHandleMut data structures

examples/error_packet.rs, src/err.rs, src/genl.rs, src/nl.rs
Closes #116 
@phip1611 Does this resolve #116 for you?
=> Allow room in error structure for payload as a buffer to be passed back

.github/workflows/main.yml, src/rtnl.rs
=> Add real tests

examples/ctrl-list.rs, examples/getips.rs, src/iter.rs, src/socket.rs
=> Do not assume that the packet will not be an ACK in NlSocketHandle::recv

examples/ctrl-list.rs, examples/genl_stream.rs, examples/route-list.rs, neli-proc-macros/src/derive_frombytes.rs, neli-proc-macros/src/shared.rs, src/consts/macros.rs, src/lib.rs, src/nl.rs, src/socket.rs, src/types.rs
Related to #156
Closes #148 
Closes #105
=> Update route-list example and fix debugging

src/rtnl.rs
Closes #158 
Closes #159 
@Kloenk Can you verify that this resolves #158? I made a PR to make the coding style more consistent with `Nlattr`.
=> Fix initial size calculation for Rtattr

src/types.rs
Closes #164
@reticenceji Can you take a look at this PR? I've kept your commits to give you credit for reporting and fixing the bug and added an additional commit to clean up some of the usage of size calculation. If this resolves your problem, I'll merge it!
=> Fix alignment issues in attribute size calculation

.githooks/pre-commit, .github/workflows/main.yml, Cargo.toml, examples/Cargo.toml, examples/async_nl80211.rs, src/nl.rs, src/socket.rs
Closes #166
Closes #165 
@isomer Can you confirm that this fixes both bugs on your end?
=> Fix bug in tokio usage and failure to handle empty netlink packet padding

src/types.rs
=> Test for alignment regression

neli-proc-macros/src/neli_enum.rs, neli-proc-macros/src/shared.rs, src/consts/nl.rs
Closes #133 
Hi @phip1611! Take a look if you'd like. I've added the documentation and it should resolve the above linked issue.
=> Add documentation for NlmF::Request and fix neli-proc-macros to support this

neli-proc-macros/src/derive_size.rs, src/genl.rs
Closes #106 
@chrboe Please take a look if you'd like!
=> Add user specific header

.githooks/pre-commit, .github/workflows/main.yml, examples/Cargo.toml, examples/nl80211.rs
=> Make nl80211 example compile with async feature enabled or disabled

src/socket.rs
@hube12 This closes #142 and #145. I gave you attribution as I based some of this off of your original code.
=> Add functionality to get socket PID

src/consts/macros.rs, src/types.rs
Closes #178 
@isomer Any thoughts?
=> Allow converting flag sets from bitmasks

examples/create-nested-attributes.rs, src/genl.rs, src/rtnl.rs
These make it easier to build attributes with nested attributes within
them.
=> Add `nest` builder methods to `Nlattr` and `Rtattr`

src/socket.rs, src/utils.rs
=> Fix bug found by Valgrind

CHANGELOG.md, Cargo.toml, examples/custom_generic_nl_family_custom_types.rs, examples/error_packet.rs, examples/extack.rs, examples/genl_stream.rs, examples/getips.rs, examples/lookup_id.rs, examples/neli.rs, examples/route-list.rs, neli-proc-macros/Cargo.toml, neli-proc-macros/src/derive_frombytes.rs, src/consts/macros.rs, src/err.rs, src/genl.rs, src/router/asynchronous.rs, src/router/synchronous.rs, src/rtnl.rs, src/socket/asynchronous.rs, src/socket/shared.rs, src/socket/synchronous.rs
Closes #147 
Closes #221
Closes #218
Closes #216 
Closes #20
=> v0.7.0-rc2

src/rtnl.rs
=> Regression test race condition

examples/nl80211.rs
Update the nl80211 example to print out a couple of attributes. As it stands currently, the output is this on my machine with one radio:
```Bash
$ cargo run --example nl80211
Compiling neli v0.7.0-rc2 (/home/alex/dev/linux_net/nl80211_rust/neli)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.56s
Running `target/debug/examples/nl80211`
msg=UnrecognizedConst(36)
msg=UnrecognizedConst(3)
```
After the changes, the output is this:
```Bash
$ cargo run --example nl80211
Compiling neli v0.7.0-rc2 (/home/alex/dev/linux_net/nl80211_rust/neli)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.79s
Running `target/debug/examples/nl80211`
Wiphy:      0
WiphyName:  phy0
```
=> Update nl80211 example

src/rtnl.rs
=> Fix incorrect datatype in Ifaddrmsg

src/utils.rs
=> Add overflow checking for NetlinkBitArray

src/socket/shared.rs
=> Use C type for setsockopt

Cargo.toml, examples/getlink-err.rs, src/consts/nl.rs, src/nl.rs, src/router/asynchronous.rs, src/router/synchronous.rs, src/socket/asynchronous.rs, src/socket/shared.rs, src/socket/synchronous.rs
=> Add API to get status of strict checking

src/rtnl.rs
@sbrivio-rh I won't merge until I've confirmed I've solved all of your issues. Can you confirm that this at least resolves the test failure that it targets? I'm happy to do testing on my end to if you can point me to how I can run it.
=> Fix rta deserialization test for big endian

src/types.rs
Currently, Buffer will forward the implementations of FromBytesWithInput and ToBytes to the generic implementation of Vec<_>. Is implementation is quite inefficient when the contained element is small (like u8) and there might be many elements (like a Buffer).
I don't see any way to specialise the Vec<u8> case, so I've implemented FromBytesWithInput and ToBytes directly for Buffer.
A very simple benchmark with 1500 bytes show these results:
- From Buffer: 27.94ns/call
- From Vec<u8>: 862.63ns/call
- To Buffer: 28.34ns/call
- To Vec<u8>: 1288.43ns/call
This shows a massive improvement when Buffer is used.
Additionally, I've added Into<Vec<u8>> to Buffer to easily retrieve the stored Vec.
---
Most of the time netlink is only used for slow actions. However sometimes, there can be quite large …
=> Directly implement FromBytesWithInput and ToBytes for Buffer

Cargo.toml, examples/create-nested-attributes.rs, neli-proc-macros/Cargo.toml, neli-proc-macros/src/derive_frombytes.rs, neli-proc-macros/src/derive_header.rs, neli-proc-macros/src/derive_size.rs, neli-proc-macros/src/derive_tobytes.rs, neli-proc-macros/src/lib.rs, neli-proc-macros/src/neli_enum.rs, neli-proc-macros/src/shared.rs, src/attr.rs, src/consts/genl.rs, src/err.rs, src/genl.rs, src/iter.rs, src/lib.rs, src/nl.rs, src/router/asynchronous.rs, src/router/synchronous.rs, src/rtnl.rs, src/socket/asynchronous.rs, src/socket/shared.rs, src/socket/synchronous.rs, src/types.rs
=> Update to Rust edition 2024

.github/workflows/main.yml, neli-proc-macros/src/derive_frombytes.rs, neli-proc-macros/src/shared.rs
=> Optionally get the buffer for deserialization, avoiding panic if index is out of bounds

src/nl.rs, src/rtnl.rs
- `Nlmsghdr::get_payload()`
- `Ifaddrmsg::ifa_index`
=> Small doc comment improvements
